"""Fixed relationship user subscription

Revision ID: 113a24f15e1a
Revises: 697a673f98a9
Create Date: 2023-12-02 21:16:23.675750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113a24f15e1a'
down_revision: Union[str, None] = '697a673f98a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
