"""Add column is_cover on propertyImages

Revision ID: 32a0e1f846d0
Revises: b29256081c9a
Create Date: 2023-11-05 14:48:11.258314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32a0e1f846d0'
down_revision: Union[str, None] = 'b29256081c9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_images', sa.Column('is_cover', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_images', 'is_cover')
    # ### end Alembic commands ###
