"""Added is_featured and is_prioritized columns on property

Revision ID: 472468dc3c67
Revises: 054b89e49434
Create Date: 2023-11-29 17:20:53.839846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472468dc3c67'
down_revision: Union[str, None] = '054b89e49434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('is_prioritized', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_subscribed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('subscription_expiry_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_expiry_date')
    op.drop_column('users', 'is_subscribed')
    op.drop_column('properties', 'is_prioritized')
    op.drop_column('properties', 'is_featured')
    # ### end Alembic commands ###
