"""Added table subscription and subscriptiontype

Revision ID: 697a673f98a9
Revises: 472468dc3c67
Create Date: 2023-11-30 08:54:50.981002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '697a673f98a9'
down_revision: Union[str, None] = '472468dc3c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
